
adjective = input("Enter an adjective: ")
adjective2 = input("Enter an adjective: ")
ty_of_a_bird = input("Enter a type of a bird: ")
room_in_a_house = input("Enter a room in the house: ")
verb = input("Enter a verb[past tense]: ")
verb2 = input("Enter an verb: ")
name = input("Enter a relative's name: ")
noun = input("Enter a noun: ")

print("It was a " + adjective + ",cold November day.")
print("I woke up to the " + adjective2 + " smell of")
print(ty_of_a_bird + " roasting in the")
print(room_in_a_house + " downstairs")
print("I " + verb + " down the stairs to see if I could help")
print(" " + verb2 + " the dinner.")
print("My mom said,see if " + name + " needs a fresh ")
print("" + noun + ".")
